trigger:
- main  # Adjust this to your default branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the build agent


steps:
# Step 1: Install the required JDK (Java 17)
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Step 2: Checkout the code
- script: |
    echo "Setting JAVA_HOME to JDK 17 location."
    java -version
  displayName: 'Check Java Version'
# Step 3: Run the Gradle build
- checkout: self
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean build'
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/**/*.xml'
    javaHomeOption: 'Path'    
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
    options: |
      -Dspring.datasource.url=jdbc:postgresql://$(POSTGRES_PORT_5432_TCP_ADDR):$(POSTGRES_PORT_5432_TCP_PORT)/$(POSTGRES_ENV_POSTGRES_DB)
      -Dspring.datasource.username=$(POSTGRES_ENV_POSTGRES_USERNAME)
      -Dspring.datasource.password=$(POSTGRES_ENV_POSTGRES_PASSWORD)
      -Dspring.profiles.active=$(SPRING_PROFILES_ACTIVE)

# Step 4: Archive the build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/libs'
    ArtifactName: 'alfio'
    publishLocation: 'Container'
