trigger:
- main  # Adjust this to your default branch

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu image for the build agent

steps:
# Step 1: Install the required JDK (Java 17)
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# Step 2: Set JAVA_HOME and confirm Java version
- script: |
    export JAVA_HOME=$(JAVA_HOME_17_X64)
    export PATH=$JAVA_HOME/bin:$PATH
    echo "JAVA_HOME is set to $JAVA_HOME"
    java -version
  displayName: 'Set JAVA_HOME and Check Java Version'

# Step 3: Configure Gradle to use Java 17
- script: |
    echo "org.gradle.java.home=$JAVA_HOME" >> gradle.properties
    cat gradle.properties
  displayName: 'Configure Gradle to Use Java 17'

# Step 4: Checkout the code
- checkout: self

# Step 5: Run the Gradle build
- task: Gradle@3
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'clean build'
    publishJUnitResults: true
    testResultsFiles: '**/build/test-results/**/*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME)'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
    options: |
      -Dspring.datasource.url=jdbc:postgresql://$(POSTGRES_PORT_5432_TCP_ADDR):$(POSTGRES_PORT_5432_TCP_PORT)/$(POSTGRES_ENV_POSTGRES_DB)
      -Dspring.datasource.username=$(POSTGRES_ENV_POSTGRES_USERNAME)
      -Dspring.datasource.password=$(POSTGRES_ENV_POSTGRES_PASSWORD)
      -Dspring.profiles.active=$(SPRING_PROFILES_ACTIVE)

# Step 6: Archive the build artifacts
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'build/libs'
    ArtifactName: 'alfio'
    publishLocation: 'Container'
